### ISSUE TITLE
[BUG] Next.js pre-render build error, cannot read property of undefined

### ISSUE THREAD

**Issue by yurixander** [webb-tools/webb-dapp#2037]
I encountered a strange bug regarding Next.js, in which TypeScript would not report any static, compile-time errors, but when building the project with Next.js, it would fail with the following: `TypeError: Cannot read properties of undefined (reading 'Account')`.

In this case, it was attempting to read the enum value `Account` from `PagePath` enum, which was correctly defined and imported, so there technically shouldn't be any problem. The vague description given off by Next.js error also makes this hard to debug what the true problem is.

I ended up changing the usage of the enum to be string constants instead for the paths, at least temporarily, until this problem can be tracked down and fixed. It is worth noting that @devpavan04 has also experienced this issue before, and also the error wasn't occurring before [the PR in which I started encountering the problem](https://github.com/webb-tools/webb-dapp/pull/2035#issuecomment-1949482495).

There doesn't seem to be any actual type errors or compile-time errors, so it may be more related to some internal issue in Next.js. Needs further investigation.

### Build log
```
> nx run tangle-dapp:build:production

   ▲ Next.js 14.1.0
   Creating an optimized production build ...
 ✓ Compiled successfully
   Skipping linting
   Checking validity of types ...
   Collecting page data ...
   Generating static pages (0/8) ...
   Generating static pages (2/8)
 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
 ⚠ metadata.metadataBase is not set for resolving social open graph or twitter images, using "http://localhost:3000". See https://nextjs.org/docs/app/api-reference/functions/generate-metadata#metadatabase
   Generating static pages (4/8)
TypeError: Cannot read properties of undefined (reading 'Account')
    at 45622 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:46138)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 87153 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:45579)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 23841 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:39193)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 14694 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:65882)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 35005 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:115091)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
Error occurred prerendering page "/claim". Read more: https://nextjs.org/docs/messages/prerender-error
TypeError: Cannot read properties of undefined (reading 'Account')
    at 45622 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:46138)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 87153 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:45579)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 23841 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:39193)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 14694 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:65882)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
    at 35005 (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/chunks/5203.js:1:115091)
    at t (/Users/yuri/work/webb-dapp/dist/apps/tangle-dapp/.next/server/webpack-runtime.js:1:143)
   Generating static pages (6/8)
 ✓ Generating static pages (8/8)
> Export encountered errors on following paths:
	/claim/page: /claim
Error occurred while trying to run the build command
1

 ————————————————————————————————————————————————————————————————————————————————————————————————————————————————————————

 >  NX   Ran target build for project tangle-dapp and 14 task(s) they depend on (47s)

    ✖    1/15 failed
    ✔    14/15 succeeded [13 read from cache]
```

**Comment by AtelyPham** [comment]
Close as the bug has been resolved.
