### ISSUE TITLE
[Bug] Bridge Relayer Withdraw is not working

### ISSUE THREAD

**Issue by nepoche** [webb-tools/webb-dapp#266]
Attempt a bridge relayer withdraw with a relayer selected. Receive this in the console:

```
Error: Attempt to use a relayer which does not support the mixer
    at Function.from (webb-error.class.ts:47:12)
    at u.getFees (web3-bridge-withdraw.ts:83:27)
    at async Withdraw.tsx:52:9
```

**Comment by nepoche** [comment]
Confirmed works on:
- webb-dapp: `9f89328f`
- protocol-substrate: `9cd3709e`
- relayer: `b2f0b52ab`
